### ISSUE TITLE
lesson 10 bug

### ISSUE THREAD

**Issue by robinlant** [SuperSimpleDev/javascript-course#21]
https://supersimple.dev/projects/dom-with-css/
line 114
<img width="474" alt="image" src="https://github.com/SuperSimpleDev/javascript-course/assets/104492072/5d71aa94-1b0d-469a-979c-f87d45754605">
<img width="301" alt="image" src="https://github.com/SuperSimpleDev/javascript-course/assets/104492072/b2b1ff49-e236-41e6-b91b-b175cd0a111b">
it is written that under 40 + 10 but in code under 35 
This problem is only on suspersimle.dev
In code from 10 lesson all ok
<img width="550" alt="image" src="https://github.com/SuperSimpleDev/javascript-course/assets/104492072/371b01f6-754d-4596-ab31-7e458684b36b">

**Comment by vishalsingh2972** [comment]
@SuperSimpleDev can you assign this to me !
