### ISSUE TITLE
Questioning the use of eval(), security issue?

### ISSUE THREAD

**Issue by T0raT** [SuperSimpleDev/javascript-course#43]
A quick search on mdn web docs tells me [eval() is a huge security risk and is slower than the alternatives.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#never_use_eval!l)

I understand for beginners' sake this might be an easier way to make a calculator. But if the aim is to go from beginner to pro, why isn't a warning given to the students regarding eval()'s security risk, or even discussed at all. I still see eval() being in the course solution up to lesson 10.

Why is this?

**Comment by T0raT** [comment]
For all beginners, just remind yourself constantly using eval() is that it's usually never a good idea.

**Comment by SuperSimpleDev** [comment]
Thanks for this. Using `eval()` is to make it easier to create the calculator project. I'll add a note in the exercises that it's only for learning purposes and to avoid using it in real world projects.

**Comment by T0raT** [comment]
Thanks for addressing the issue Simon!

**Comment by T0raT** [comment]
> Thanks for this. Using `eval()` is to make it easier to create the calculator project. I'll add a note in the exercises that it's only for learning purposes and to avoid using it in real world projects.

Thanks for addressing the issue Simon!
